# Numpy Brush Up

###Library for operations related with linear algebra 

In [1]:

import numpy as np

###Generation of numpy array from Python lists

In [2]:
list_1 = [10,2,35,6]

In [3]:
np.array(list_1)

array([10,  2, 35,  6])

In [4]:
list_2=[[1,4],[-8,3]]

In [5]:
np.array(list_2)

array([[ 1,  4],
       [-8,  3]])

###Generation of numpy array using built in techniques

In [6]:
np_arr1=np.arange(3,14,2)
print(np_arr1)

[ 3  5  7  9 11 13]


In [7]:
np_arr2=np.ones(5)  # vector 1-D
print(np_arr2)

[1. 1. 1. 1. 1.]


In [8]:
np_arr3=np.ones((2,5)) # matrix 2-D
print(np_arr3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
np_arr4=np.zeros(9)  # vector 1-D
print(np_arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
np_arr5=np.zeros((2,5)) # matrix 2-D
print(np_arr5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
np_arr6=np.linspace(1,10,3)  # in 3 points
print(np_arr6)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
linspace


NameError: ignored

In [ ]:
np_arr7=np.eye(6)
print(np_arr7)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [11]:
np_arr8=np.random.rand(4)  #Span [0,1]
print(np_arr8)

[0.86884483 0.81105195 0.95636533 0.35883865]


In [12]:
np_arr9=np.random.rand(4,5)
print(np_arr9)

[[0.69408285 0.68853744 0.77226425 0.80320203 0.33533538]
 [0.2504796  0.55588919 0.74303069 0.79408967 0.43327464]
 [0.58467394 0.29923099 0.72376255 0.74043958 0.50506082]
 [0.83033355 0.94720659 0.73503951 0.10517561 0.96258903]]


In [13]:
np_arr9.reshape(10,2)   #number of elements should be same

array([[0.69408285, 0.68853744],
       [0.77226425, 0.80320203],
       [0.33533538, 0.2504796 ],
       [0.55588919, 0.74303069],
       [0.79408967, 0.43327464],
       [0.58467394, 0.29923099],
       [0.72376255, 0.74043958],
       [0.50506082, 0.83033355],
       [0.94720659, 0.73503951],
       [0.10517561, 0.96258903]])

In [14]:
print(np_arr9.max())  #val

print(np_arr9.argmax())  #loc


0.962589031783728
19


In [ ]:
np_arr9.shape  #to know the size

(4, 5)

In [ ]:
np_arr9.dtype

dtype('float64')

In [ ]:
np_arr9 > 0.2

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Scipy Brush Up

In [15]:

from scipy import linalg

import numpy as np
numpy_mat = np.array([[3,2,2],[5,5,2],[7,8,69]])
linalg.det(numpy_mat)

335.00000000000006

In [ ]:
from scipy import linalg
import numpy as np
arr11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
linalg.det(arr11)


0.0

In [ ]:
EW, EV = linalg.eig(numpy_mat)
print(EW)
print(EV)

[69.48501546+0.j  0.70830143+0.j  6.80668311+0.j]
[[-0.03105513 -0.64577793 -0.39161821]
 [-0.03339063  0.76317248 -0.90600067]
 [-0.99895978 -0.0232083   0.16061746]]


In [17]:
from numpy import poly1d
p = poly1d([3,2,1])
print(p)

   2
3 x + 2 x + 1


In [18]:
print(p*p)

   4      3      2
9 x + 12 x + 10 x + 4 x + 1


In [19]:
print(p.deriv())

 
6 x + 2


In [ ]:
#Computation of FFT
from scipy.fftpack import fft,ifft
import numpy as np
#Numpy array generation
x = np.array([1.0, 1.0, 1.0, 1.0])

#Applying the fft function
y = fft(x)
print(y)

[4.+0.j 0.+0.j 0.+0.j 0.-0.j]


In [ ]:
yinv = ifft(y)

print (yinv)

[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
