In [ ]:
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df1 = pd.read_excel('my_own_dataset.xlsx')

In [ ]:
df1

x1  x2  x3  x4  label
0    1   2   3   4     30
1    2  31  32   2   1993
2    2  32  12   2   1176
3   32   3  43   3   2891
4    3  43   2  34   3018
5    8   4   5   5    130
6   56  56  56   3   9417
7    4   5  43  45   3915
8    4  34   7  78   7305
9   68  67  56  65  16474
10   5  56   5  56   6322
11  56   6   5   4   3213
12   3   5  34  65   5415
13  65  76  76   8  15841
14  87  87   9  76  20995
15   7   8  67  78  10686
16  78   6  67  67  15098
17  67  87   7  67  16596
18  67  67   7  65  13252

In [ ]:
X = df1[['x1','x2','x3','x4']]
print(X)

    x1  x2  x3  x4
0    1   2   3   4
1    2  31  32   2
2    2  32  12   2
3   32   3  43   3
4    3  43   2  34
5    8   4   5   5
6   56  56  56   3
7    4   5  43  45
8    4  34   7  78
9   68  67  56  65
10   5  56   5  56
11  56   6   5   4
12   3   5  34  65
13  65  76  76   8
14  87  87   9  76
15   7   8  67  78
16  78   6  67  67
17  67  87   7  67
18  67  67   7  65


In [ ]:
y = df1[['label']]
print(y)

    label
0      30
1    1993
2    1176
3    2891
4    3018
5     130
6    9417
7    3915
8    7305
9   16474
10   6322
11   3213
12   5415
13  15841
14  20995
15  10686
16  15098
17  16596
18  13252


In [ ]:
x_var=X.to_numpy() 
print(x_var)

[[ 1  2  3  4]
 [ 2 31 32  2]
 [ 2 32 12  2]
 [32  3 43  3]
 [ 3 43  2 34]
 [ 8  4  5  5]
 [56 56 56  3]
 [ 4  5 43 45]
 [ 4 34  7 78]
 [68 67 56 65]
 [ 5 56  5 56]
 [56  6  5  4]
 [ 3  5 34 65]
 [65 76 76  8]
 [87 87  9 76]
 [ 7  8 67 78]
 [78  6 67 67]
 [67 87  7 67]
 [67 67  7 65]]


In [ ]:
y_var=y.to_numpy()
print(y_var)

[[   30]
 [ 1993]
 [ 1176]
 [ 2891]
 [ 3018]
 [  130]
 [ 9417]
 [ 3915]
 [ 7305]
 [16474]
 [ 6322]
 [ 3213]
 [ 5415]
 [15841]
 [20995]
 [10686]
 [15098]
 [16596]
 [13252]]


In [ ]:
y_var.ravel()

array([   30,  1993,  1176,  2891,  3018,   130,  9417,  3915,  7305,
       16474,  6322,  3213,  5415, 15841, 20995, 10686, 15098, 16596,
       13252])

In [ ]:
# Create logistic regression Model
model1 = linear_model.LogisticRegression(solver='liblinear',C=100)

In [ ]:
# Train the classifier
model1.fit(x_var,y_var.ravel())

LogisticRegression(C=100, solver='liblinear')

In [ ]:
# Testing of model1
pred_class = model1.predict(np.array([[1,3,3,4]]))
print(pred_class)

[30]
